(function(){'use strict';var f;function aa(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var n=aa(this),ba="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},p;
if("function"==typeof Object.setPrototypeOf)p=Object.setPrototypeOf;else{var q;a:{var ca={a:!0},t={};try{t.__proto__=ca;q=t.a;break a}catch(a){}q=!1}p=q?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var u=p;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var v=this||self;function w(a){return a};function x(a,b){a=parseInt(a.getAttribute(b),10);isNaN(a)&&(a=1);return a}function y(a,b,c){a=z(a,b,c);return 0<a?a:c}function z(a,b,c){a=parseFloat(a.getAttribute(b));isFinite(a)||(a=c);return a}function A(a,b,c){return a.hasAttribute(b)?a.getAttribute(b):c};var da="gwd-blinds gwd-door-wipe gwd-fade gwd-iris-wipe gwd-push gwd-radial-wipe gwd-rotate gwd-slice gwd-split-push gwd-stripe-wipe gwd-venetian-blinds gwd-wipe gwd-zigzag".split(" ");var B;function E(a){this.g=a}E.prototype.toString=function(){return this.g.toString()};E.prototype.i=!0;E.prototype.h=function(){return this.g.toString()};var F;try{new URL("s://g"),F=!0}catch(a){F=!1}var ea=F,fa={};var ha={};function G(a){this.g=a;this.i=!0}G.prototype.h=function(){return this.g.toString()};G.prototype.toString=function(){return this.g.toString()};function H(a){return"gwd-page"==a.tagName.toLowerCase()||"gwd-page"==a.getAttribute("is")}function ia(a){if(H(a))return a;for(;a&&9!=a.nodeType;)if((a=a.parentElement)&&H(a))return a;return null}function I(a,b,c,d){d=(void 0===d?"":d)||b;a.hasAttribute(b)?(a=a.getAttribute(b),c.setAttribute(d,a)):c.removeAttribute(d)}function J(a,b){return(a=A(a,b,""))?a.split(",").map(function(c){return c.trim()}):[]};function K(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d);return d};/*

 SPDX-License-Identifier: Apache-2.0
*/
function ja(a,b,c,d){var e=new XMLHttpRequest;e.open("GET",b);e.setRequestHeader("Content-Type","image/svg+xml");e.addEventListener("load",function(){var h=e.responseText,k=new DOMParser;if(void 0===B){var l=null,g=v.trustedTypes;if(g&&g.createPolicy){try{l=g.createPolicy("goog#html",{createHTML:w,createScript:w,createScriptURL:w})}catch(r){v.console&&v.console.error(r.message)}B=l}else B=l}h=B?B.createHTML(h):h;h=new G(h,ha);if(k=k.parseFromString(h instanceof G&&h.constructor===G?h.g:"type_error:SafeHtml",
"image/svg+xml").getElementsByTagName("svg")[0])if(k.hasAttribute("width")&&k.hasAttribute("height"))a.src=b;else{h=c;l=d;if(g=k.getAttribute("viewBox")){var m=g.match(/[\d,\.]+ [\d,\.]+ ([\d,\.]+) ([\d,\.]+)/);m&&(g=parseFloat(m[1]),m=parseFloat(m[2]),g&&m&&(l=Math.min(c/g,d/m),h=g*l,l*=m))}k.setAttribute("width",h);k.setAttribute("height",l);k=(new XMLSerializer).serializeToString(k);a.src="data:image/svg+xml;base64,"+window.btoa(k)}});e.send()};var ka=["easing","exit-urls","images","scaling","transition-duration"];function M(){var a=HTMLElement.call(this)||this;a.B=[];a.v=[];a.K=a.ja.bind(a);a.A=!1;a.ba=0;a.h=0;a.U=null;a.s=null;a.M=null;a.P=0;a.u=0;a.J=!1;a.I=!1;a.o=null;a.ca=a.ka.bind(a);a.fa=a.na.bind(a);a.ea=a.ma.bind(a);a.da=a.la.bind(a);a.O=!1;a.m=!1;a.C=null;a.D=null;a.S=!1;return a}var N=HTMLElement;M.prototype=ba(N.prototype);M.prototype.constructor=M;
if(u)u(M,N);else for(var O in N)if("prototype"!=O)if(Object.defineProperties){var P=Object.getOwnPropertyDescriptor(N,O);P&&Object.defineProperty(M,O,P)}else M[O]=N[O];f=M.prototype;
f.connectedCallback=function(){var a=this;this.l=this.clientWidth;this.i=this.clientHeight;var b=z(this,"swipe-committed-threshold",.25);this.oa=b*this.l;this.pa=b*this.i;this.qa=z(this,"swipe-threshold",.3);this.H=J(this,"images");this.N=x(this,"start-frame");this.T=1E3*y(this,"transition-duration",1);this.ha=1E3*y(this,"autoplay-frame-interval",1.5);this.W=x(this,"autoplay-loop-count");this.ga=this.hasAttribute("wrap");this.L=A(this,"scaling","stretch");this.Z=A(this,"easing","linear");this.G=A(this,
"gesture","click");this.R=this.hasAttribute("enable-interactive-transition");this.ia=this.hasAttribute("ignore-reverse-swipe");this.aa=J(this,"exit-urls");setTimeout(function(){a.j=a.firstElementChild&&-1!==da.indexOf(a.firstElementChild.tagName.toLowerCase())?a.firstElementChild:null;a.hasAttribute("has-navigation")&&!a.o&&(a.i-=36,a.o=a.ownerDocument.createElement("gwd-gallerynavigation"),a.o.setAttribute("for",a.id),a.appendChild(a.o),I(a,"navigation-highlight",a.o,"highlight"),I(a,"navigation-thumbnails",
a.o,"use-thumbnails"));a.C||(a.C=a.ownerDocument.createElement("canvas"),a.appendChild(a.C));Q(a,a.C);a.X=a.C.getBoundingClientRect();a.Y=a.C.getContext("2d");a.D||(a.D=a.ownerDocument.createElement("gwd-gesture"),a.appendChild(a.D));var c=a.D;c.addEventListener("tap",a.ca,!1);if("swipe"===a.G||"click"===a.G&&a.R)c.addEventListener("trackstart",a.fa,!1),c.addEventListener("track",a.ea,!1),c.addEventListener("trackend",a.da,!1);a.A?(a.g=-1,R(a)):(a.S=!0,a.gwdIsLoaded()||((c=ia(a))?c.gwdIsLoaded()&&
a.gwdLoad():a.gwdLoad()))},1)};f.disconnectedCallback=function(){if(this.D){var a=this.D;a.removeEventListener("tap",this.ca,!1);if("swipe"===this.G||"click"===this.G&&this.R)a.removeEventListener("trackstart",this.fa,!1),a.removeEventListener("track",this.ea,!1),a.removeEventListener("trackend",this.da,!1)}this.o&&(this.removeChild(this.o),this.o=null)};
f.attributeChangedCallback=function(a,b,c){var d=this;if(b!==c&&this.S)switch(a){case "transition-duration":this.T=1E3*y(this,"transition-duration",1);break;case "easing":this.Z=A(this,"easing","linear");break;case "scaling":this.L=A(this,"scaling","stretch");S(this);T(this,this.g,!1);break;case "exit-urls":this.aa=J(this,"exit-urls");break;case "images":this.H=J(this,"images"),this.A=!1,setTimeout(function(){d.gwdLoad()},1)}};
f.gwdLoad=function(){if(!this.A||this.S)if(this.h=this.ba=0,this.v=[],this.H.length)for(var a=this.B.length=0;a<this.H.length;a++){var b=this.ownerDocument.createElement("img");b.addEventListener("load",this.K,!1);b.addEventListener("error",this.K,!1);var c=this.H[a];"svg"===c.split(".").pop().toLowerCase()?ja(b,c,this.l,this.i):b.src=c;this.B.push(b)}else this.A=!0,K("ready",this)};f.gwdIsLoaded=function(){return this.A};
function Q(a,b){var c=window.devicePixelRatio;b.width=a.l*c;b.height=a.i*c;b.style.width=a.l+"px";b.style.height=a.i+"px";b.getContext("2d").scale(c,c)}f.ja=function(a){var b=this,c=a.target;c.removeEventListener("load",this.K,!1);c.removeEventListener("error",this.K,!1);c=this.B.indexOf(c);0<=c&&("error"===a.type&&this.B.splice(c,1),++this.ba==this.H.length&&setTimeout(function(){R(b)},1))};
function R(a){S(a);a.hasAttribute("autoplay")?a.startAutoplay():a.goToFrame(a.N,!1);a.A||(a.A=!0,K("ready",a))}f.getFrame=function(a){if(0!=this.h)return this.B[a-1]};f.goToFrame=function(a,b){b=void 0===b?!!this.j:b;this.stop(!1);this.h&&(a=U(this,a),a!=this.g&&T(this,a,b))};function T(a,b,c){c=void 0===c?!!a.j:c;K("frameactivated",a,{id:b+1});c?(a.F=b,a.U=Date.now()-(a.m?a.u*a.T:0),a.m=!1,a.V()):(a.Y.clearRect(0,0,a.l,a.i),a.Y.drawImage(a.v[b],0,0,a.l,a.i),V(a,b))}
function S(a){a.v=[];for(var b=0;b<a.B.length;b++){var c=a.B[b],d=c.naturalWidth,e=c.naturalHeight,h=!1;d&&e||(a.appendChild(c),h=!0,d=c.width,e=c.height);var k=0,l=0,g=d,m=e,r=0,L=0,C=a.l,D=a.i;"contain"===a.L?(r=Math.min(a.l/d,a.i/e),C=r*d,D=r*e,r=(a.l-C)/2,L=(a.i-D)/2):"cover"===a.L?(k=Math.max(a.l/d,a.i/e),g=a.l/k,m=a.i/k,k=(d-g)/2,l=(e-m)/2):"none"===a.L&&(l=d-a.l,g=e-a.i,k=Math.max(l/2,0),r=Math.max(-l/2,0),l=Math.max(g/2,0),L=Math.max(-g/2,0),g=Math.min(d,a.l),m=Math.min(e,a.i),C=g,D=m);d=
a.ownerDocument.createElement("canvas");Q(a,d);d.getContext("2d").drawImage(c,k,l,g,m,r,L,C,D);a.v.push(d);h&&a.removeChild(c)}a.h=a.v.length}function V(a,b){a.g!=b&&(a.g=b,K("frameshown",a,{frameIndex:a.g}),0==a.g?K("reachleftend",a):a.g==a.h-1&&K("reachrightend",a))}f.goForwards=function(){this.stop(!1);(this.ga||this.g!=this.h-1)&&this.h&&T(this,W(this,!0))};f.goBackwards=function(){this.stop(!1);(this.ga||0!=this.g)&&this.h&&T(this,W(this,!1))};
function W(a,b){return((b?a.g+1:a.g-1)+a.h)%a.h}function U(a,b){1>b?b=1:b>a.h&&(b=a.h);return b-1}f.V=function(){this.m||null===this.U||(this.u=la(this,Math.min(1,(Date.now()-this.U)/this.T)),this.s=requestAnimationFrame(this.V.bind(this)));this.j.renderAnimation(this.v[this.g],this.v[this.F],this.u);1!=this.u||this.m||(this.s&&(cancelAnimationFrame(this.s),this.s=null),this.j.resetDirection(),V(this,this.F),(this.I||this.J)&&X(this))};
function la(a,b){switch(a.Z){case "ease-in":return b*b*b;case "ease-in-out":return 3*b*b-2*b*b*b;case "ease-out":return a=1-b,1-a*a*a;default:return b}}f.startAutoplay=function(a){this.P=0;(void 0===a?0:a)||this.goToFrame(this.N,!1);this.I=!0;X(this)};f.rotateOnce=function(a){(void 0===a?0:a)||this.goToFrame(this.N,!1);this.J=!0;X(this)};function ma(a){var b=U(a,a.N);return 0==b?a.h:b}f.updateAnimationElement=function(a){this.j=a};
function X(a){if(a.J){if(a.g==ma(a)-1){a.stop(!0);return}}else if(a.I&&0!=a.W&&(a.g==ma(a)-1&&a.P++,a.P>=a.W)){a.stop(!0);return}a.M=setTimeout(function(){requestAnimationFrame(function(){a.h&&T(a,W(a,!0));a.j||X(a)})},a.ha)}function na(a){.5<=a.u?T(a,a.F,!1):T(a,a.g,!1)}
f.stop=function(a,b){b=null!=b?b:!0;this.s&&(cancelAnimationFrame(this.s),this.s=null,na(this));this.m&&(this.m=!1,na(this),this.j.resetDirection());this.M&&(clearTimeout(this.M),this.M=null);this.J?(this.J=!1,b&&K("rotateonceended",this,{completed:!!a})):this.I&&(this.I=!1,b&&K("autoplayended",this,{completed:!!a}))};
f.ka=function(){if(this.h){K("frametap",this,{id:this.g+1});var a=this.aa[this.g];if(a){if(this.stop(!1),!K("frameexit",this,{url:a}).detail.handled){if(!(a instanceof E||a instanceof E)){a="object"==typeof a&&a.i?a.h():String(a);b:{var b=a;if(ea){try{var c=new URL(b)}catch(d){b="https:";break b}b=c.protocol}else c:{c=document.createElement("a");try{c.href=b}catch(d){b=void 0;break c}b=c.protocol;b=":"===b||""===b?"https:":b}}"javascript:"===b&&(a="about:invalid#zClosurez");a=new E(a,fa)}v.open(a instanceof
E&&a.constructor===E?a.g:"type_error:SafeUrl","")}}else"click"==this.G&&this.goForwards()}};f.na=function(){this.stop(!1)};
f.ma=function(a){var b=this;if(!this.O)if(this.R&&Y(this,a.dx,a.dy,!1)){this.m||(this.m=!0,Z(this,a.dx,a.dy,function(){b.F=W(b,!0)},function(){b.F=W(b,!1)}));a=Math.abs(a.dy)>Math.abs(a.dx)?(a.clientY-this.X.top)/this.i:(a.clientX-this.X.left)/this.l;var c=this.j.getSupportedSwipeDirection();0>c[0]+c[1]&&(a=1-a);this.u=a;this.V()}else Y(this,a.dx,a.dy,!0)&&(this.O=!0,Z(this,a.dx,a.dy,this.goForwards.bind(this),this.goBackwards.bind(this)))};
f.la=function(a){this.O?this.O=!1:this.m?this.u>=this.qa?T(this,this.F):this.stop(!1,!1):Y(this,a.dx,a.dy,!1)&&Z(this,a.dx,a.dy,this.goForwards.bind(this),this.goBackwards.bind(this))};function Y(a,b,c,d){var e=Math.abs(c)>Math.abs(b),h=a.j?a.j.getSupportedSwipeDirection():[0,0];b*=h[0];c*=h[1];return(e?c:b)?a.ia&&(e?0>c:0>b)?!1:d?e?Math.abs(c)>=a.pa:Math.abs(b)>=a.oa:!0:!1}
function Z(a,b,c,d,e){Math.abs(c)>Math.abs(b)?0<c?(a.j.setDirection("toptobottom"),e()):(a.j.setDirection("bottomtotop"),d()):0<b?(a.j.setDirection("lefttoright"),e()):(a.j.setDirection("righttoleft"),d())}n.Object.defineProperties(M.prototype,{frameCount:{configurable:!0,enumerable:!0,get:function(){return this.h}},currentIndex:{configurable:!0,enumerable:!0,get:function(){return 0<this.h?this.g+1:void 0}}});n.Object.defineProperties(M,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ka}}});
customElements.define("gwd-transitiongallery",M);}).call(this);
